version: '3.8'

services:
  database:
    image: mysql:8
    command: --init-file /data/application/init.sql
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "${MYSQL_PORT:-13306}:3306"
    env_file:
      - .env
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - database
    ports:
      - "${APP_PORT-5000}:80"
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 5050:80
    environment:
      PMA_HOST: database
      UPLOAD_LIMIT: 3000000000
      GC_MAXLIFETIME: -1
      PMA_USER: "${MYSQL_USER}"
      PMA_PASSWORD: "${MYSQL_PASSWORD}"
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  mysqldata: {}
