<?php

namespace App\Enums\Person;

use Illuminate\Support\Str;
use Spatie\Enum\Enum;

/**
 * @method static self qizanAlNajjar()
 * @method static self qizanAbuRashwan()
 * @method static self juraAlLoot()
 * @method static self sheikhNasser()
 * @method static self maAn()
 * @method static self alManaraNeighborhood()
 * @method static self easternLine()
 * @method static self westernLine()
 * @method static self alMahatta()
 * @method static self alKatiba()
 * @method static self alBatanAlSameen()
 * @method static self alMaskar()
 * @method static self alMashroo()
 * @method static self hamidCity()
 * @method static self alMawasi()
 * @method static self alQarara()
 * @method static self eastKhanYounis()
 * @method static self downtown()
 * @method static self mirage()
 * @method static self european()
 * @method static self alFakhari()
 * @method static self masbah()
 * @method static self khirbetAlAdas()
 * @method static self alJaninehNeighborhood()
 * @method static self alAwda()
 * @method static self alZohourNeighborhood()
 * @method static self brazilianHousing()
 * @method static self telAlSultan()
 * @method static self alShabouraNeighborhood()
 * @method static self rafahProject()
 * @method static self zararRoundabout()
 * @method static self jabalia()
 * @method static self beitLahia()
 * @method static self beitHanoun()
 * @method static self omAlNasr()
 * @method static self nazla()
 * @method static self alZahra()
 * @method static self alMughraqa()
 * @method static self alBureij()
 * @method static self alNuseirat()
 * @method static self alMaghazi()
 * @method static self alZawaida()
 * @method static self deirAlBalah()
 * @method static self shujaiya()
 * @method static self alDaraj()
 * @method static self alTuffah()
 * @method static self alRimal()
 * @method static self alZaytoun()
 * @method static self alNasr()
 * @method static self sheikhRadwan()
 * @method static self telAlHawa()
 * @method static self sheikhAjleen()
 * @method static self alSabra()
 * @method static self alKaramah()
 * @method static self birAlNajah()
 * @method static self juhrAlDeek()
 * @method static self shatiCamp()
 */
class PersonNeighborhood extends Enum {}